apiVersion: v1
kind: LimitRange
metadata:
  name: cluster-limit-range
spec:
  limits:
    - type: Container
      max:
        cpu: "4"
        memory: "1Gi"
      default:
        cpu: "4"
        memory: "512Mi"
      defaultRequest:
        cpu: "500m"
        memory: "256Mi"
