apiVersion: v1
kind: LimitRange
metadata:
  name: cluster-limit-range
spec:
  limits:
    - type: Container
      default:
        memory: "512Mi"
      defaultRequest:
        cpu: "2"
        memory: "256Mi"
