apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        kind: {{ .Values.app.kind }}
      {{- if eq .Values.app.kind "grpc" -}}
      annotations:
        sidecar.istio.io/userVolume: '[{"name":"descriptor","configMap":{"name":"{{ .Values.app.name }}-proto-descriptor","items":[{"key":"proto.pb","path":"proto.pb"}]}}]'
        sidecar.istio.io/userVolumeMount: '[{"name":"descriptor","mountPath":"/etc/envoy"}]'
      {{- end }}
    spec:
      containers:
        - name: business-application
          image: "{{ .Values.image.registry }}/{{ .Values.image.name | default .Values.app.name }}:{{ .Values.app.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.app.kind }}-api
              containerPort: {{ .Values.app.ports.api }}
            - name: http-management
              containerPort: {{ .Values.app.ports.management }}
          startupProbe:
            tcpSocket:
              port: {{ .Values.app.ports.api }}
            initialDelaySeconds: 2
            periodSeconds: 1
            failureThreshold: 60
          livenessProbe:
            tcpSocket:
              port: {{ .Values.app.ports.api }}
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: {{ if ne .Values.app.kind "grpc" }}/actuator{{end}}/health/readiness
              port: http-management
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: environment-config
          env:
            - name: SERVER_PORT
              value: {{ .Values.app.ports.api | quote }}
            - name: MANAGEMENT_PORT
              value: {{ .Values.app.ports.management | quote }}
