{{ if eq .Values.app.kind "grpc" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-proto-descriptor
binaryData:
  proto.pb: |-
  {{ .Files.Get "proto.pb" | b64enc |  indent 4 }}
{{ end }}
