apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
spec:
  ports:
    - name: {{ .Values.app.kind }}-backend
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.ports.api }}
  type: ClusterIP
  selector:
    app: {{ .Values.app.name }}
